### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Jadhielv**
@vueuse/core from 4.4.1 to 4.11.2
shiki from 0.9.4 to 0.10.1
vue-router from 4.0.6 to 4.0.14
shiki-renderer-svg from 0.9.4 to 0.10.1
vuex from 4.0.0 to 4.0.1

### CODE REVIEW

**Comment by Jadhielv** [comment]
@octref As soon as you've time, please check this PR

**Comment by Jadhielv** [comment]
@octref As soon as you've time, please check this PR

**Comment by Jadhielv** [comment]
@octref / @antfu / @leafac / @orta As soon as you've time, please check this PR

**Comment by orta** [comment]
Please don't @ folks for minor dependency upgrades - is there a specific reason you wanted to update the packages?

**Comment by Jadhielv** [comment]
@orta Alright.

ℹ️ Btw, I think keeping dependencies up-to-date makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect the project.

**Pull request closed without merging**
